CREATE TABLE AccountPaymentCardInfoRecord (
  recordID INT AUTO_INCREMENT PRIMARY KEY,
  PaymentCardType VARCHAR(255),
  CardNumber VARCHAR(255),
  CardHolderName VARCHAR(255),
  CardExpYear INT,
  CardExpMonth INT,
  CardCVV2 VARCHAR(255),
  BillingAddress1 VARCHAR(255),
  BillingAddress2 VARCHAR(255),
  BillingCity VARCHAR(255),
  BillinZip VARCHAR(255),
  BillingState VARCHAR(255),
  BillingCountry VARCHAR(255),
  BillingPhone VARCHAR(255),
  BillinEmailAddress VARCHAR(255),
  CCApprovalDate DATE,
  CCApprovalCode VARCHAR(255),
  CDenialDate DATE,
  CDenialCode VARCHAR(255),
  UseAVS VARCHAR(255),
  PriceBeforeTax DECIMAL(10, 2),
  TaxAmount DECIMAL(10, 2),
  TransactionType VARCHAR(255),
  AuthComments VARCHAR(255),
  AuthStatus VARCHAR(255),
  AuthSource VARCHAR(255),
  AuthResponse VARCHAR(255),
  TransDate DATE,
  TransTime TIME,
  PS2000Data VARCHAR(255),
  SettlementDate DATE,
  SettlementCode VARCHAR(255),
  CCTSResponseCode VARCHAR(255),
  SettlementBatchId INT,
  SettlementBatchSeq INT,
  SettlementApprovalCode VARCHAR(255),
  SettlementComments VARCHAR(255),
  SettlementStatus VARCHAR(255),
  AStoBBSTxnId VARCHAR(255),
  SubsId VARCHAR(255),
  AcctName VARCHAR(255),
  CC1TimeChargeTxnSeq VARCHAR(255),
  CustSupportName VARCHAR(255),
  ChargeBackCaseNumber VARCHAR(255),
  GetCreditForceTxnSeq VARCHAR(255),
  ShippingInfoRecord VARCHAR(255),
  CVV2Response VARCHAR(255)
);