-- MySQL Script generated by MySQL Workbench
-- Sat Jul  1 20:20:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stmserver
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stmserver
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stmserver` DEFAULT CHARACTER SET utf8 ;
USE `stmserver` ;

-- -----------------------------------------------------
-- Table `UserRegistry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserRegistry` (
  `UniqueID` INT NOT NULL AUTO_INCREMENT,
  `UniqueUserName` VARCHAR(256) NOT NULL,
  `AccountCreationTime` DATETIME NOT NULL,
  `OptionalAccountCreationKey` VARCHAR(45) NOT NULL DEFAULT 'Egq-pe-y',
  `SteamLocalUserID` VARCHAR(45) BINARY NOT NULL,
  `UserType` INT NOT NULL DEFAULT 1,
  `SaltedAnswerToQuestionDigest` VARCHAR(512) BINARY NOT NULL,
  `PassphraseSalt` VARCHAR(512) BINARY NOT NULL,
  `AnswerToQuestionSalt` VARCHAR(512) BINARY NOT NULL,
  `PersonalQuestion` VARCHAR(256) BINARY NOT NULL,
  `SaltedPassphraseDigest` VARCHAR(512) BINARY NOT NULL,
  `LastRecalcDerivedSubscribedAppsTime` VARCHAR(45) BINARY NOT NULL,
  `Cellid` VARCHAR(45) BINARY NOT NULL,
  `AccountEmailAddress` VARCHAR(256) NOT NULL,
  `Banned` VARCHAR(45) BINARY NOT NULL DEFAULT '00 00',
  `AccountLastModifiedTime` VARCHAR(45) BINARY NOT NULL DEFAULT 'e0 e0 e0 e0 e0 e0 e0 00',
  PRIMARY KEY (`UniqueID`))
ENGINE = MyISAM;

CREATE UNIQUE INDEX `UniqueID_UNIQUE` ON `UserRegistry` (`UniqueID` ASC);


-- -----------------------------------------------------
-- Table `SteamSubscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SteamSubscriptions` (
  `SubscriptionID` INT NOT NULL,
  `Name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`SubscriptionID`))
ENGINE = MyISAM;

CREATE UNIQUE INDEX `SubscriptionID_UNIQUE` ON `SteamSubscriptions` (`SubscriptionID` ASC);


-- -----------------------------------------------------
-- Table `SteamSub_APPS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SteamSub_APPS` (
  `UniqueID` INT NOT NULL AUTO_INCREMENT,
  `SteamSubscriptions_SubscriptionID` INT NOT NULL,
  `AppList` VARCHAR(512) NULL,
  PRIMARY KEY (`UniqueID`, `SteamSubscriptions_SubscriptionID`))
ENGINE = MyISAM;

CREATE UNIQUE INDEX `UniqueID_UNIQUE` ON `SteamSub_APPS` (`UniqueID` ASC);


-- -----------------------------------------------------
-- Table `AccountSubscriptionsRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AccountSubscriptionsRecord` (
  `UniqueID` INT NOT NULL AUTO_INCREMENT,
  `UserRegistry_UniqueID` INT NOT NULL,
  `SubscriptionID` VARCHAR(45) BINARY NOT NULL,
  `SubscribedDate` VARCHAR(45) BINARY NOT NULL DEFAULT 'e0 e0 e0 e0 e0 e0 e0 00',
  `UnsubscribedDate` VARCHAR(45) BINARY NULL DEFAULT '00 00 00 00 00 00 00 00',
  `SubscriptionStatus` VARCHAR(45) BINARY NOT NULL DEFAULT '01 00',
  `StatusChangeFlag` VARCHAR(45) BINARY NOT NULL DEFAULT '00',
  `PreviousSubscriptionState` VARCHAR(45) BINARY NOT NULL DEFAULT '1f 00',
  PRIMARY KEY (`UniqueID`, `UserRegistry_UniqueID`))
ENGINE = MyISAM;

CREATE UNIQUE INDEX `UniqueID_UNIQUE` ON `AccountSubscriptionsRecord` (`UniqueID` ASC);

CREATE INDEX `fk_AccountSubscriptionsRecord_UserRegistry1_idx` ON `AccountSubscriptionsRecord` (`UserRegistry_UniqueID` ASC);

CREATE INDEX `fk_AccountSubscriptionsRecord_SteamSub_apps1_idx` ON `AccountSubscriptionsRecord` (`SubscriptionID` ASC);


-- -----------------------------------------------------
-- Table `DerivedSubscribedAppsRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DerivedSubscribedAppsRecord` (
  `UniqueID` INT NOT NULL AUTO_INCREMENT,
  `UserRegistry_UniqueID` INT NOT NULL,
  `AppID` INT NULL,
  `Field2` VARCHAR(45) NULL,
  PRIMARY KEY (`UniqueID`))
ENGINE = MyISAM;

CREATE UNIQUE INDEX `UniqueID_UNIQUE` ON `DerivedSubscribedAppsRecord` (`UniqueID` ASC);

CREATE INDEX `fk_DerivedSubscribedAppsRecord_UserRegistry1_idx` ON `DerivedSubscribedAppsRecord` (`UserRegistry_UniqueID` ASC);


-- -----------------------------------------------------
-- Table `AccountPrepurchasedInfoRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AccountPrepurchasedInfoRecord` (
  `UniqueID` INT NOT NULL AUTO_INCREMENT,
  `TypeOfProofOfPurchase` VARCHAR(45) NULL,
  `BinaryProofOfPurchaseToken` VARCHAR(45) NULL,
  `TokenRejectionReason` VARCHAR(45) NULL,
  `AStoBBSTxnId` VARCHAR(45) NULL,
  `SubsId` VARCHAR(45) NULL,
  `AcctName` VARCHAR(45) NULL,
  `CustSupportName` VARCHAR(45) NULL,
  PRIMARY KEY (`UniqueID`))
ENGINE = MyISAM;

CREATE UNIQUE INDEX `UniqueID_UNIQUE` ON `AccountPrepurchasedInfoRecord` (`UniqueID` ASC);


-- -----------------------------------------------------
-- Table `AccountExternalBillingInfoRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AccountExternalBillingInfoRecord` (
  `UniqueID` INT NOT NULL AUTO_INCREMENT,
  `ExternalAccountName` VARCHAR(256) NULL,
  `ExternalAccountPassword` VARCHAR(256) NULL,
  PRIMARY KEY (`UniqueID`))
ENGINE = MyISAM;

CREATE UNIQUE INDEX `UniqueID_UNIQUE` ON `AccountExternalBillingInfoRecord` (`UniqueID` ASC);


-- -----------------------------------------------------
-- Table `AccountPaymentCardReceiptRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AccountPaymentCardReceiptRecord` (
  `recordID` INT NOT NULL AUTO_INCREMENT,
  `PaymentCardTypeID` INT NULL DEFAULT NULL,
  `CardNumber` VARCHAR(255) NULL DEFAULT NULL,
  `CardHolderName` VARCHAR(255) NULL DEFAULT NULL,
  `field4` VARCHAR(255) NULL DEFAULT NULL,
  `field5` VARCHAR(255) NULL DEFAULT NULL,
  `field6` VARCHAR(255) NULL DEFAULT NULL,
  `BillingAddress1` VARCHAR(255) NULL DEFAULT NULL,
  `BillingAddress2` VARCHAR(255) NULL DEFAULT NULL,
  `BillingCity` VARCHAR(255) NULL DEFAULT NULL,
  `BillingZip` VARCHAR(255) NULL DEFAULT NULL,
  `BillingState` VARCHAR(255) NULL DEFAULT NULL,
  `BillingCountry` VARCHAR(255) NULL DEFAULT NULL,
  `CCApprovalCode` VARCHAR(255) NULL DEFAULT NULL,
  `PriceBeforeTax` DECIMAL(10,2) NULL DEFAULT NULL,
  `TaxAmount` DECIMAL(10,2) NULL DEFAULT NULL,
  `TransDate` DATE NULL DEFAULT NULL,
  `TransTime` TIME NULL DEFAULT NULL,
  `AStoBBSTxnId` VARCHAR(255) NULL DEFAULT NULL,
  `ShippingCost` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`recordID`))
ENGINE = MyISAM;

CREATE UNIQUE INDEX `recordID_UNIQUE` ON `AccountPaymentCardReceiptRecord` (`recordID` ASC);


-- -----------------------------------------------------
-- Table `AccountSubscriptionsBillingInfoRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AccountSubscriptionsBillingInfoRecord` (
  `UniqueID` INT NOT NULL AUTO_INCREMENT,
  `UserRegistry_UniqueID` INT NOT NULL,
  `Subscriptionid` VARCHAR(45) BINARY NOT NULL,
  `AccountPaymentCardInfoRecord` VARCHAR(45) BINARY NOT NULL,
  `AccountPrepurchasedInfoRecord_UniqueID1` INT NOT NULL,
  `AccountExternalBillingInfoRecord_UniqueID` INT NOT NULL,
  `AccountPaymentCardReceiptRecord_recordID` INT NOT NULL,
  PRIMARY KEY (`UniqueID`, `UserRegistry_UniqueID`, `AccountPrepurchasedInfoRecord_UniqueID1`))
ENGINE = MyISAM;

CREATE UNIQUE INDEX `UniqueID_UNIQUE` ON `AccountSubscriptionsBillingInfoRecord` (`UniqueID` ASC);

CREATE INDEX `fk_AccountSubscriptionsBillingInfoRecord_UserRegistry1_idx` ON `AccountSubscriptionsBillingInfoRecord` (`UserRegistry_UniqueID` ASC);

CREATE INDEX `fk_AccountSubscriptionsBillingInfoRecord_AccountPrepurchase_idx` ON `AccountSubscriptionsBillingInfoRecord` (`AccountPrepurchasedInfoRecord_UniqueID1` ASC);

CREATE INDEX `fk_AccountSubscriptionsBillingInfoRecord_AccountExternalBil_idx` ON `AccountSubscriptionsBillingInfoRecord` (`AccountExternalBillingInfoRecord_UniqueID` ASC);

CREATE INDEX `fk_AccountSubscriptionsBillingInfoRecord_AccountPaymentCard_idx` ON `AccountSubscriptionsBillingInfoRecord` (`AccountPaymentCardReceiptRecord_recordID` ASC);


-- -----------------------------------------------------
-- Table `UserAppAccessRightsRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UserAppAccessRightsRecord` (
  `UniqueID` INT NOT NULL AUTO_INCREMENT,
  `UserRegistry_UniqueID` INT NOT NULL,
  `AppID` INT NOT NULL,
  `Rights` VARCHAR(45) NULL,
  PRIMARY KEY (`UniqueID`, `UserRegistry_UniqueID`))
ENGINE = MyISAM;

CREATE UNIQUE INDEX `UniqueID_UNIQUE` ON `UserAppAccessRightsRecord` (`UniqueID` ASC);

CREATE INDEX `fk_UserAppAccessRightsRecord_UserRegistry1_idx` ON `UserAppAccessRightsRecord` (`UserRegistry_UniqueID` ASC);


-- -----------------------------------------------------
-- Table `CustSupportAccountRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CustSupportAccountRecord` (
  `UniqueID` INT NOT NULL AUTO_INCREMENT,
  `AccountSubscriptionsRecord_UniqueID` INT NOT NULL,
  `UserRegistry_UniqueID` INT NOT NULL,
  `AccountStatus` VARCHAR(45) NULL,
  PRIMARY KEY (`UniqueID`, `AccountSubscriptionsRecord_UniqueID`, `UserRegistry_UniqueID`))
ENGINE = MyISAM;

CREATE UNIQUE INDEX `UniqueID_UNIQUE` ON `CustSupportAccountRecord` (`UniqueID` ASC);

CREATE INDEX `fk_CustSupportAccountRecord_AccountSubscriptionsRecord1_idx` ON `CustSupportAccountRecord` (`AccountSubscriptionsRecord_UniqueID` ASC);

CREATE INDEX `fk_CustSupportAccountRecord_UserRegistry1_idx` ON `CustSupportAccountRecord` (`UserRegistry_UniqueID` ASC);


-- -----------------------------------------------------
-- Table `VACRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VACRecord` (
  `UniqueID` INT NOT NULL AUTO_INCREMENT,
  `CustSupportAccountRecord_UniqueID` INT NOT NULL,
  `BannedAtTime` VARCHAR(45) NULL,
  `BannedFromTime` VARCHAR(45) NULL,
  `BannedUntilTime` VARCHAR(45) NULL,
  `Reason` VARCHAR(45) NULL,
  `Infractions` VARCHAR(45) NULL,
  `AccountCreationIP` VARCHAR(45) NULL,
  PRIMARY KEY (`UniqueID`))
ENGINE = MyISAM;

CREATE UNIQUE INDEX `UniqueID_UNIQUE` ON `VACRecord` (`UniqueID` ASC);

CREATE INDEX `fk_VACRecord_CustSupportAccountRecord1_idx` ON `VACRecord` (`CustSupportAccountRecord_UniqueID` ASC);


-- -----------------------------------------------------
-- Table `SteamApplications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SteamApplications` (
  `AppID` INT NOT NULL,
  `Name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`AppID`))
ENGINE = MyISAM;

CREATE UNIQUE INDEX `AppID_UNIQUE` ON `SteamApplications` (`AppID` ASC);


-- -----------------------------------------------------
-- Table `ccCardType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccCardType` (
  `uniqueid` INT NOT NULL,
  `card_type` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`uniqueid`))
ENGINE = MyISAM;

CREATE UNIQUE INDEX `uniqueid_UNIQUE` ON `ccCardType` (`uniqueid` ASC);

CREATE USER 'stmadmin' IDENTIFIED BY 'admin';

GRANT SELECT ON TABLE * TO 'stmadmin';
GRANT ALL ON * TO 'stmadmin';
GRANT SELECT, INSERT, TRIGGER ON TABLE * TO 'stmadmin';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'stmadmin';
GRANT EXECUTE ON ROUTINE * TO 'stmadmin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
