CREATE TABLE IF NOT EXISTS SteamSubscriptions (
    SubscriptionID INT PRIMARY KEY,
    Name VARCHAR(255)
);



CREATE TABLE IF NOT EXISTS SteamSubscriptions (SubscriptionID INT PRIMARY KEY, Name VARCHAR(255));
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (0, 'Steam');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (1, 'Half-Life Platinum Pack');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (2, 'Day of Defeat');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (3, 'Condition Zero');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (4, 'Cyber Cafe');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (5, 'ATI Bundle');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (6, 'Condition Zero');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (7, 'Condition Zero');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (8, 'Valve Premier Pack');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (9, 'Half-Life 2 Bronze');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (10, 'Half-Life 2 Silver');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (11, 'Half-Life 2 Retail Standard');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (12, 'Half-Life 2 Retail Collectors');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (13, 'Half-Life 2 Gold');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (14, 'HL2 Complimentary Edition');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (15, 'AMD Bundle');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (16, 'DoD:S Beta Test');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (17, 'Valve Test App 120 Sub');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (18, 'Valve Test App 1000 Sub');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (19, 'Half-Life 2 Game of the Year');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (20, 'Counter-Strike 1 Anthology');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (21, 'Half Life 1 Anthology');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (22, 'Counter-Strike Source');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (23, 'Half-Life 2 Platinum');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (24, 'Half-Life 1 Classic');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (25, 'Day of Defeat: Source');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (26, 'Online Multiplayer');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (27, 'DoD_Review');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (29, 'Team Fortress Classic');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (30, 'Day of Defeat');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (31, 'Deathmatch Classic');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (32, 'Opposing Force');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (33, 'Ricochet');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (34, 'Half-Life 1');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (35, 'Half-Life: Blue Shift');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (36, 'Half-Life 2');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (37, 'Counter-Strike: Source');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (38, 'Half-Life 1: Source');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (39, 'Half-Life 2: Deathmatch');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (40, 'Half-Life 1 Anthology');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (41, 'Counter-Strike 1 Anthology');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (42, 'Source Multiplayer Pack');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (43, 'Source Premier Pack');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (44, 'Valve Complete Pack');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (45, 'Rag Doll Kung Fu');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (46, 'Rag Doll Kung Fu Complementary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (47, 'Day of Defeat: Source Promo');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (48, 'Valve Test App 1309 Sub');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (49, 'School Lab');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (50, 'Gift Pack');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (51, 'Valve Test App 1100');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (52, 'Rag Doll Kung Fu Test');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (53, 'Red Orchestra Beta');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (54, 'Darwinia');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (55, 'Darwinia Complementary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (56, 'Day of Defeat Source');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (57, 'Space Empires IV Deluxe');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (58, 'SCS - Dangerous Waters');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (59, 'Space Empires IV Deluxe Complementary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (60, 'SCS - Dangerous Waters Complementary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (61, 'Steam Master');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (62, 'Press Master');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (63, 'Red Orchestra');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (64, 'Red Orchestra Retail');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (65, 'Red Orchestra Complementary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (66, 'GNA/WEG Tournament Promotion');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (67, 'VTT');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (68, 'Valve Complete Pack Complementary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (69, 'SiN Episodes Emergence');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (70, 'Sin Episode 1');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (71, 'Rag Doll Kung Fu');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (72, 'Earth 2160');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (73, 'Earth 2160 Complementary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (74, 'Valve Test Sub 74');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (75, 'Sin Episode 1 DE');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (76, 'Condition Zero and Counter-Strike');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (77, 'Half-Life 2: Episode One');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (78, 'SiN Episodes Emergence DE');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (79, 'Half-Life 2: Episode One');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (80, 'Source Premier Pack');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (81, 'Valve Complete Pack');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (82, 'Half-Life 2: Lost Coast and Deathmatch');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (83, 'SiN Episodes Emergence OEM');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (84, 'Half-Life 2: Episode One OEM');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (85, 'Shadowgrounds');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (86, 'Shadowgrounds Complimentary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (87, 'The Ship Beta');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (88, 'Sci-Fi Strategy Pack');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (89, 'SiN Episodes Emergence Germany');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (90, 'The Ship');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (91, 'The Ship Complimentary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (92, 'Day of Defeat Source');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (93, 'SiN Episodes Emergence');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (94, 'Jagged Alliance 2');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (95, 'Disciples II Gold');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (96, 'Jagged Alliance 2 / Disciples II Gold Combo');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (97, 'Jagged Alliance 2 Complimentary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (98, 'Disciples II Gold Complimentary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (99, 'X2/X3 Complimentary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (100, 'X2: The Threat');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (101, 'X3: Reunion');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (102, 'X2: The Threat / X3: Reunion');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (103, 'Birth of America');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (104, 'Iron Warriors');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (105, 'Birth of America Complimentary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (106, 'Iron Warriors Complimentary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (107, 'Sci-Fi Game Pack');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (108, 'Half-Life 2 Classic');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (109, 'The Ship Retail');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (110, 'Uplink Beta');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (111, 'Sniper Elite Beta');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (112, 'Uplink');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (113, 'Darwinia / Uplink');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (114, 'GTI Racing');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (115, 'Xpand Rally');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (116, 'GTI/Xpand Pack');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (117, 'GTI/Xpand Pack with MOMO Racing Wheel');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (118, 'GTI Racing Retail');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (119, 'GTI/Xpand Pack Retail');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (120, 'PopCap Complimentary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (121, 'Bejeweled 2 Deluxe');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (122, 'Bejeweled Deluxe');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (123, 'Zuma Deluxe');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (124, 'Feeding Frenzy 2 Deluxe');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (125, 'Bookworm Deluxe');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (126, 'Chuzzle Deluxe');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (127, 'Insaniquarium Deluxe');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (128, 'Dynomite Deluxe');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (129, 'Iggle Pop Deluxe');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (130, 'Pizza Frenzy');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (131, 'Typer Shark Deluxe');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (132, 'AstroPop Deluxe');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (133, 'Heavy Weapon Deluxe');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (134, 'Rocket Mania Deluxe');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (135, 'Hammer Heads Deluxe');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (136, 'Big Money Deluxe');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (137, 'Talismania Deluxe');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (138, 'Puzzle Pack');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (139, 'Action Pack');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (140, 'Thinking Pack');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (141, 'Puzzle + Action Pack');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (142, 'Thinking + Action Pack');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (143, 'Puzzle + Thinking Pack');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (144, 'The Complete PopCap Collection');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (145, 'Dark Messiah Steam Beta');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (146, 'Majesco Complimentary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (147, 'Strategy First Complimentary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (148, 'Counter-Strike: Source');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (149, 'Counter-Strike');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (150, 'Half-Life 2: Deathmatch / Half-Life 2: Lost Coast');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (151, 'Half-Life 2 Holiday Pack 2006');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (152, 'Half-Life 2 Holiday 2006');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (153, 'BloodRayne');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (154, 'BloodRayne 2');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (155, 'Advent Rising');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (156, 'Defcon');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (158, 'ValveTestSub 158 Complimentary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (159, 'Defcon Demo Beta');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (160, 'Defcon Beta');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (161, 'Space Empires V Complimentary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (162, 'Psychonauts Beta');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (163, 'ValveTestSub163 Complimentary');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (164, 'Dark Messiah');
INSERT INTO SteamSubscriptions (SubscriptionID, Name) VALUES (165, 'Sci-Fi Game Pack');
